#!/bin/bash
#PBS -l nodes=1:ppn=4,vmem=4gb,walltime=2:00:00
#PBS -N tractanalysisprofiles
#PBS -V

module load singularity 2> /dev/null

singularity exec -e docker://brainlife/mcr:neurodebian1604-r2017a ./compiled/main


count=$(ls images/*.png | wc -l)
NUMFILES=`cat numfiles.txt`

if [ "$count" ==  "$NUMFILES" ];
then
	echo 0 > finished
else
	echo "output missing"
	echo 0 > finished
	exit 0
fi
