#!/bin/bash
#PBS -l nodes=1:ppn=4,vmem=28gb,walltime=6:00:00
#PBS -N tractanalysisprofiles
#PBS -V

singularity exec -e docker://brainlife/mcr:neurodebian1604-r2017a ./compiled/main

count=$(ls images/*.png | wc -l)
NUMFILES=`cat numfiles.txt`
cp product.json ./profiles/
if [ "$count" !=  "$NUMFILES" ];
then
	echo "not all output generated"
	exit 1
fi
