#!/bin/bash
#PBS -k o
#PBS -l nodes=1:ppn=16,walltime=1:00:00

if [ $ENV == "IUHPC" ]; then
	cd $PBS_O_WORKDIR
	module load matlab
	module load spm
fi

rm -rf images
rm -f images.json
rm -f numfiles.txt

export MATLABPATH=$MATLABPATH:$SERVICE_DIR
matlab -nodisplay -nosplash -r main
