#!/bin/bash
#PBS -l nodes=1:ppn=8:dc2,walltime=0:10:00
#PBS -N tractanalysisprofiles
#PBS -V


if [ $ENV == "IUHPC" ]; then
	cd $PBS_O_WORKDIR
	module load matlab
	module load spm
fi


rm -rf images
rm -f images.json
rm -f numfiles.txt

export MATLABPATH=$MATLABPATH:$SERVICE_DIR
matlab -nodisplay -nosplash -r main
count=$(ls images/*.png | wc -l)
NUMFILES=`cat numfiles.txt`

if [ "$count" ==  "$NUMFILES" ];
then
	echo 0 > finished
else
	echo "output missing"
	echo 0 > finished
	exit 0
fi
